/* config.h. Generated by cmake from config.h.cmake */

/* Defined if your compiler supports some byte swap functions */
#define   HAVE_GCC_BYTESWAP 1
/* #undef HAVE_GLIBC_BYTESWAP */
/* #undef HAVE_MSC_BYTESWAP */
/* #undef HAVE_MAC_BYTESWAP */
/* #undef HAVE_OPENBSD_BYTESWAP */

/* Defined if your compiler supports some atomic operations */
/* #undef HAVE_STD_ATOMIC */
/* #undef HAVE_BOOST_ATOMIC */
#define   HAVE_GCC_ATOMIC 1
/* #undef HAVE_MAC_ATOMIC */
/* #undef HAVE_WIN_ATOMIC */
/* #undef HAVE_IA64_ATOMIC */

/* Defined if your compiler supports some safer version of vsprintf */
#define   HAVE_VSNPRINTF 1
/* #undef HAVE_VSPRINTF_S */

/* Defined if you have libz */
/* #undef HAVE_ZLIB */

/* Indicates whether debug messages are shown even in release mode */
/* #undef TRACE_IN_RELEASE */

#define TESTS_DIR "E:/Qt/Libs/taglib-1.10/tests/"
